### ISSUE TITLE
Dust Filtration

### ISSUE THREAD

**Issue by lastcoolnameleft** [TheLab-ms/facilities#2]
- [x] Specify which Dust Filtration System to purchase
- [x] Specify "resting place" for Dust Filtration System
- [x] Propose purchase to Board
- [x] Purchase Dust Filtration System
- [x] Collect Dust Filtration System
- [x] Install Dust Filtration System
- [ ] Dedicated voltage run Issue #10
- [ ] Re-install door

**Comment by cloudislands** [comment]
Specify which Dust Filtration System to purchase:


**Central Machinery 70 gal. 2 HP Heavy Duty High Flow High Capacity Dust Collector
Harbor Freight  https://www.harborfreight.com/2-hp-industrial-5-micron-dust-collector-97869.html
$199 less 20% coupon= $160 + tax**
add $100 for misc connections and cyclone 2-phase collection if needed but most tools have standard connections built in.

  Specify "resting place" for Dust Filtration System
**Stick in a corner as phase 1 would be completly mobile with connection hose to move when needed.  Phase 2 option would be to install conduits to each station but this could wait for bigger space.**


  Propose purchase to Board
**consider this proposed?  I'm at meeting tonght.**

  Purchase Dust Filtration System
**could be up and running this weekend**

  Install Dust Filtration System
**Phase 1 set up only.  start scheduling small projects**

**Comment by cloudislands** [comment]
[Quote Report Plano MS.pdf](https://github.com/TheLab-ms/facilities/files/2193952/Quote.Report.Plano.MS.pdf)

**Comment by cloudislands** [comment]
quote as promised from woodcraft with discount

**Comment by lastcoolnameleft** [comment]
System has been paid for and will be picked up on Monday.  I'm excited it's almost here!

**Comment by cloudislands** [comment]
the item is still sitting at terminal in Garland,  they have marked it to expedite.  should be tomorrow but will check tuesday

**Comment by lastcoolnameleft** [comment]
We need to re-install the two doors (entrance to the workshop room and the wiring room).  

@cloudislands Is there anything else we need to do to mark off this item?  Does the electrical work still need to be done?

**Comment by cloudislands** [comment]
Didnt notice doors were off,  I can help today with some notice just lmk.

On electrical,  It seemed like we were all in agreement that we can safely function and launch as is but the follow up with the free resource for the work.  I wpuld say u could lower the priority with the update for the follow up.

Greg gave me the go to schedule a project day for the miter station we discussed using pocket hole method.  Fyi

**Comment by cloudislands** [comment]
I'll be in lab within hour btw
